server:
  port: ${APP_PORT:8080}
  address: 0.0.0.0

spring:
  application:
    name: urlshortener
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
    url: jdbc:postgresql://${DB_HOST_NAME:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:user123}
    password: ${DB_PASSWORD:pass123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
short-url:
  allowed-characters: ${ALLOWED_CHARS:abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789}
  key-length: ${KEY_LENGTH:6}

app:
  base-url: ${APP_BASE_URL:http://localhost:${APP_PORT:8080}}
